{
 "title": "ARM64 CI status",
 "tags": [
  "arm64",
  "aarch64",
  "ci"
 ],
 "time": { "from": "now-24h", "to": "now+1d" },
 "panels": [
  {
   "title": "Failing Github Actions CIs",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "project_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "ci_job_name.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "hide": true,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "ci_provider:github-actions AND status:failure",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Failing CircleCI jobs",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "project_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "ci_job_name.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "ci_provider:circleci AND status:failed",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Successful Github Actions",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "project_name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "ci_job_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "ci_provider:github-actions AND status:success",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}